Spellchecking and typography fixes
movim/movim pull request #612
Opened 2018-03-25 14:07 UTC by ujdhesa

Changed `...` in `…`; ` !` in `!` (no preceding space) and fixed some spellchecking errors.

2018-03-25 14:09 UTC, linkmauve approved these changes
LGTM!

2018-03-25 14:09 UTC, linkmauve commented on locales/en.po
> +msgid "You don't have Javascript enabled.  Good luck with that."
JavaScript, with an uppercase S.

2018-03-25 14:09 UTC, linkmauve commented on locales/en.po
> +msgid "An error occurred :"
No space before the colon.

2018-03-25 14:12 UTC, linkmauve commented on locales/en.po
> +msgid "Your server doesn't support XMPP Pubsub persistence."
“doesn’t”, not “doesn't” (note the apostrophe vs. the single quote).

2018-03-25 14:26 UTC, linkmauve requested changes
I just noticed you modified the .po file, while it should be done in the sources (and then the .po regenerated from that), I don’t know if it’s possible to merge the .po into the source code as is.

2018-03-25 14:26 UTC, linkmauve commented on locales/en.po
> +msgid "This server doesn’t exists"
“doesn’t exist”

2018-03-25 14:26 UTC, linkmauve commented on locales/en.po
> +msgid "It seems that this community doesn’t exists anymore. Do you want to remove it from your subscriptions?"
“doesn’t exist”

2018-03-25 14:26 UTC, linkmauve commented on locales/en.po
> +msgid "Do you want do join automaticaly this Chat Room?"
“Do you want to automatically join”

2018-03-25 14:26 UTC, linkmauve commented on locales/en.po
> +msgid "I’m "
This will need to be changed in the source, as it will be very hard to translate in languages with a non-English word order.

2018-03-25 14:26 UTC, linkmauve commented on locales/en.po
> +msgid "It seems that this group doesn’t exists anymore. Do you want to remove it from your subscriptions?"
“doesn’t exist”, also two spaces after a sentence point.

2018-03-25 14:26 UTC, linkmauve commented on locales/en.po
> +msgid "Please pay attention! By making your profile public, all the information listed below will be available for all the Movim users and on the whole Internet."
Two spaces after a sentence “!”.

2018-05-18 19:01 UTC, edhelas commented
Thoses files are generated, it would be better to update the .ini files instead :)

2018-08-23 21:25 UTC, closed without merging